export const soundList = [
    'amateurs',
    'birthdayDinner',
    'croissant',
    'dontSayThat',
    'girlDinner',
    'hateritis',
    'isThatAChicken',
    'IYGIYGI',
    'kimStopTakingSelfies',
    'lightWorkNoReaction',
    'michaelNo',
    'myOpinion',
    'theresPeopleThatAreDying',
    'urFine',
    'youreDoingAmazingSweetie',
]