export const soundList = [
    'amateurs',
    'tati-birthday-dinner',
    'coulda-dropped-my-croissant',
    'aria-dont-say-that',
    'bruh',
    'tiktok-girl-dinner',
    'hateritis',
    'is-that-a-chicken',
    'kim-stop-taking-pictures',
    'light-work-no-reaction',
    'the-office-michael-no',
    'thats-my-opinion',
    'kim-theres-people-that-are-dying',
    'you-have-to-say-that-ur-fine',
    'vine-boom',
    'kim-ur-doing-amazing-sweetie',
]