export const soundList = [
    'amateurs',
    'tati-birthday-dinner',
    'croissant',
    'aria-dont-say-shat',
    'girl-dinner',
    'mic-hateritis',
    'kylie-is-that-a-chicken',
    'kim-pictures',
    'light-work-no-reaction',
    'michael-no',
    'my-opinion',
    'theres-people-that-are-dying',
    'ur-fine',
    'youre-doing-amazing-sweetie',
]